### ISSUE TITLE
`zipp.Path` is not Path-like enough for `open`

### ISSUE THREAD

**Issue by xtofl** [jaraco/zipp#110]
I'm not sure if this is a problem with `open` not recognizing `zipp.Path` or with `zipp.Path` not implementing the right interface.

But we can observe a mysterious incompatibility between `zipp.Path` and standard library functions.

Disclaimer: I realize a more thorough type-analytical paper could probably be written about the relations between `zipp.Path` and `pathlib.Path`, describing Liskov's Substitution Principle and including some in-depth type-theory and category theoretical proofs, but I'm not there yet :).

## Observed behavior:

```python
>>> zipfile.is_zipfile("some-zip.zip")
True
>>> zipfile.is_zipfile(zipp.Path("some-zip.zip"))
Traceback (most recent call last):
  Cell In[10], line 1
    zipfile.is_zipfile(zipp.Path("some-zip.zip"))
  File /usr/lib/python3.8/zipfile.py:208 in is_zipfile
    with open(filename, "rb") as fp:
TypeError: expected str, bytes or os.PathLike object, not Path
```
cf. https://github.com/python/cpython/blob/a5fef800d31648d19cecc240a2fa0dc71371753e/Lib/zipfile/__init__.py#L243

```python
>>> pathlib.Path("some-zip.zip")
PosixPath('some-zip.zip')
>>> pathlib.Path(zipp.Path("some-zip.zip"))
Traceback (most recent call last):
  Cell In[13], line 1
    pathlib.Path(zipp.Path("some-zip.zip"))
  File /usr/lib/python3.8/pathlib.py:1042 in __new__
    self = cls._from_parts(args, init=False)
  File /usr/lib/python3.8/pathlib.py:683 in _from_parts
    drv, root, parts = self._parse_args(args)
  File /usr/lib/python3.8/pathlib.py:667 in _parse_args
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not Path

```

## Expected behavior:

```python
>>> zipfile.is_zipfile(zipp.Path("some-zip.zip"))
True
>>> pathlib.Path(zipp.Path("some-zip.zip"))
PosixPath('some-zip.zip')
```

**Comment by xtofl** [comment]
I have code that expects a `Path`, and will accept zip files and regular folders alike (think `.docx` files or their unzipped folders).  We're handling some kind of proprietary recordings that are represented in either way.

In case the code receives a path that points to a zip file (and not a folder), it will continue with 

```python
def transparent_unzip(recording: Path) -> Path:
  if zipfile.is_zipfile(recording):
    return zipp.Path(recording)
  else:
    return recording

def handle(folder_or_zip: Path):
  recording = transparent_unzip(folder_or_zip)
  schema = (recording / "marker").read_text()
  ...
```



## Out-of Scope Expectation

> cannot be path-like because it has no direct representation it the file system

This statement would imply that e.g. files in `/tmp` cannot be accessed like other files (`/tmp` normally has an in-memory file system mounted onto it).  Same goes for `/proc` etc...  So I think we have to disregard that: the hierarchy can, at least conceptually, be navigated deeply into the zip file - even into a nested zip file if need be.

It is navigating _out of_ the zip (`/path/to/a.zip/../a.zip` is a zip file, too) file that could pose big problems, and I'm definitely not going that far.  Nor the `/path/to/outer.zip/with/inner.zip` (which is a little easier).

## Just Good Enough Scope Expectation

So yes, `zipp.Path` object would be 'path-like' when pointing to the root would solve my use case.

**Comment by xtofl** [comment]
Today I bumped onto another occurrence of the same behavior: extracting an image from a zip file:

```python
import PIL.Image
import zipp
root = zipp.Path("/path/to.zip")
with Image.open(root / "image.png") as img:
  ...
```

This [`Image.open`](https://github.com/python-pillow/Pillow/blob/f790878853993429bd3aa64cf75e1be5248d153f/src/PIL/Image.py#L3237) assumes a path-like object, but `zipp.Path` is not.  As a consequence, the library treats the object like a file object.

**Comment by jaraco** [comment]
> Today I bumped onto another occurrence of the same behavior

This use-case wouldn't be solved by making the root object Path-like.

What could `zipp.Path("/path/to.zip", "image.png")` possibly represent to `Image.open()` to allow it to function? There's no path on the file system that contains "image.png". In this case, PIL should add support for [Traversable](https://docs.python.org/3/library/importlib.resources.abc.html#importlib.resources.abc.Traversable) objects, at which point `Image.open()` could load the contents from the item in the zipfile.

How does this new expectation affect your thinking about the original concern?

**Comment by jaraco** [comment]
@xtofl Any more thoughts on my questions?

**Comment by jaraco** [comment]
> There are other libraries offering Path-like objects that have nothing to do with the file system (directly), e.g. [cloudpathlib](https://pypi.org/project/cloudpathlib/). This is why I expected `zipp` to do the same.

The goals of `zipp.Path` (and `zipfile.Path`) are very similar to those of cloudpathlib. Are cloudpathlib Paths compatible with `PIL`? Yes, it seems so.

The reason cloudpath is able to offer a File-like interface is because it caches everything locally. That is, for every file in the cloud that's accessed, it creates a copy on the local disk, and when an application like `PIL` requests `os.fspath()`, it [returns the cached local path](https://github.com/drivendataorg/cloudpathlib/blob/08b018b36f90f89003e0c9e5ebd19030b41c2433/cloudpathlib/cloudpath.py#L316-L319).

For `zipp.Path` to do the same, it would need to create and manage a cache of "local" files and every time a file is accessed by that method, it would extract that file from the zip file to somewhere in the local cache, then pass that filename to the caller. It would have no hope of cleaning it up, as there's no indication of when the file path is no longer needed.

For cloudpath users, that expectation is fine. Users expect as a matter of course that the content in the cloud copied to their local disk and that they'll need to manage the lifecycle of that cache. Users of `zipp.Path` probably don't have the same expectation. At least, as it's designed, the content is always stored and referenced in its canonical location (the zip file), which may not even itself be stored on disk (it could be in memory or even in a [network location](https://blog.jaraco.com/tiny-hack-extracting-small-file-from-a-large-zip/)). 

I'm reluctant to create interfaces that silently leak data onto the user's hard disk, especially as this behavior is also built into Python. It's conceivable the file could be extracted to a `tempdir()` and rely on periodic cleanup for managing the lifecycle of accumulated artifacts (do all operating systems perform periodic cleanup of temp?).

It seems to me it would be preferable for applications like PIL to support the Traversable interface and thus not require that the content have a filename and storage on the local disk to be accessible.

----

Note that if what you need is a temporary file system handle to a Traversable, `importlib.resources` [provides the `as_file` context manager](https://docs.python.org/3/library/importlib.resources.html#importlib.resources.as_file).

Perhaps that's all you need:

```python
import zipp
root = zipp.Path("/path/to.zip")

import PIL.Image
import importlib.resources
with importlib.resources.as_file(root / "image.png") as local, Image.open(local) as img:
  ...
```

Does that satisfy your needs?

**Comment by xtofl** [comment]
> Note that if what you need is a temporary file system handle to a Traversable 

That's a nice trick!  I wasn't aware of it, thanks.  I'll definitely look into it.

> Users of zipp.Path probably don't have the same expectation.

At least one user does :).  

> For zipp.Path to do the same, it would need to create and manage a cache of "local" files

At first I thought this seems like an implementation choice, or even a configurable policy: favor speed over footprint.  But reading a bit more, I start to understand the `__fspath__` member would be required to be `PathLike`, so to abide, we _would_ require a filesystem file, which would be of no real use since it would be ephemeral.

Anyhow, thanks, I will give it some thought.
