### ISSUE TITLE
Pypi egg_info incorrect

### ISSUE THREAD

**Issue by ohimors** [jaraco/zipp#31]
The `importlib-metadata` library has a dependency on the zipp module.  The zipp module in pypi appears to have incorrect egg_info as signified by the following warning when attempting to satisfy the dependency:

"Downloading https://files.pythonhosted.org/packages/69/d2/daa94177e934b0b1b0780f5c856c41c248a88b2f43c046ae23afb0116ec0/zipp-2.0.1.tar.gz
  Running setup.py (path:/tmp/pip-build-CIm5mP/zipp/setup.py) egg_info for package zipp produced metadata for project name unknown. Fix your #egg=zipp fragments."

Was there a change in the egg_info from version 1.0?  Can the change be reverted?

**Comment by raarts** [comment]
Why was this closed? I'm having the same problem.

**Comment by ohimors** [comment]
It looks like this project literally dropped 2.7 support by removing the version in setup.py.  There are at least 2 options here:

- add a pegged version of zipp to your project to ensure that the module is available
- upgrade to 3.x. 

I do think they should revert the setup.py so it doesn't break 2.7 stacks so folks can still retrieve a compatible version.  

Any other options?

**Comment by raarts** [comment]
For me it breaks ansible docker-compose on CentOS 7 (which depends on python 2.7).
So I can only fix this by maintaining my own version of ansible which if course is a drag.

@jaraco are you still working on this repo?

**Comment by jaraco** [comment]
> It looks like this project literally dropped 2.7 support by removing the version in setup.py.

This project, along with dozens of others, relies on setuptools_scm to resolve the version. In recent releases (2.0.0), a later version of setuptools_scm (and setuptools) is required in order to invoke the behavior. This change has nothing to do with Python 2.7, except that support for Python 2.7 was coincidentally dropped in the 2.0.0 release.

Possible workarounds / solutions are as follows:

- pin to zipp 1.x (`zipp<2`).
- ensure you have `setuptools>=42` and `setuptools_scm[toml]>=3.4.1` as declared in the pyproject.toml build-system.requires before building the package.
- install the package with pip 9 or later (which will use wheels to pull down the pre-built versions and will only pull versions that are viable on your version of Python).
- Use another PEP 517/518-compliant builder/installer.

**Comment by raarts** [comment]
Upgrading pip worked for me. Thanks!
