### ISSUE TITLE
Distribution version not detected with importlib_metadata

### ISSUE THREAD

**Issue by cphang99** [jaraco/zipp#51]
zipp version tested: 3.1.0

Also see https://gitlab.com/libreml/libreml/-/jobs/499145882#L2292

This seems to be related to https://bugs.archlinux.org/task/65348 Toml should be installed, but for some reason the same bug results.

**Comment by jaraco** [comment]
Zipp [requires a few packages to build](https://github.com/jaraco/zipp/blob/02b914eca955b8f1912c519303b0abaca4a4dab2/pyproject.toml#L2). Those packages will automatically be installed if using a [PEP 518](https://www.python.org/dev/peps/pep-0518/) compatible installer. I believe pip 10 and later are PEP 518 compatible. Alternately, before building zipp, you could hard-code those requirements and make sure they're available.

This issue is unrelated to `importlib_metadata`, except for the fact that `importlib_metadata` has a dependency on zipp. Any package that has a dependency on zipp is going to have a problem buliding/installing if they're not using a PEP 518 compatible installer.

I'd be happy to help the Buildstream project or ArchLinux to develop a workflow that honors PEP 518. For those projects, feel free to file a bug at [pypa/packaging-problems](/pypa/packaging-problems) and ping me on it. Be sure to describe the problem your project is trying to solve, what is the technique it currently uses (if not `pip install`), and where it goes wrong. Please try as much as possible to distill the problem into a simple, repeatable process (maybe a Docker environment) that can replicate the issue.

**Comment by jaraco** [comment]
For completeness, a demonstration that installing importlib_metadata produces a zipp distribution installed with a valid version:

```
draft $ pip-run importlib_metadata                                                                                                                                        
Collecting importlib_metadata
  Using cached importlib_metadata-1.6.0-py2.py3-none-any.whl (30 kB)
Collecting zipp>=0.5
  Using cached zipp-3.1.0-py3-none-any.whl (4.9 kB)
Installing collected packages: zipp, importlib-metadata
Successfully installed importlib-metadata-1.6.0 zipp-3.1.0
Python 3.8.2 (v3.8.2:7b3ab5921f, Feb 24 2020, 17:52:18) 
[Clang 6.0 (clang-600.0.57)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import importlib_metadata as md
>>> md.version('zipp')
'3.1.0'
```
